apiVersion: v1
kind: Service
metadata:
  name: lens-template-service-python
  labels:
    name: lens-template-service-python
spec:
  selector:
    app: lens-template-service-python
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
