apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lens-template-service-python
spec:
  hosts:
    - "*"
  gateways:
    - gh-gateway
  http:
    - match:
        - uri:
            prefix: /external/
      rewrite:
        uri: "/"
      route:
        - destination:
            host: lens-template-service-python.default.svc.cluster.local
            port:
              number: 3000
      corsPolicy:
        allowMethods:
          - GET
          - POST
          - OPTIONS
        allowOrigins:
          - exact: "*"
        allowHeaders:
          - "content-type"
          - "Accept"